//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmortizacionDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NorthwindEntities : DbContext
    {
        public NorthwindEntities()
            : base("name=NorthwindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Prestamo> Prestamo { get; set; }
    
        public virtual int EnviarCorreo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EnviarCorreo");
        }
    
        public virtual int TablaAmortizacion(Nullable<double> principal, Nullable<int> mes, Nullable<double> interes)
        {
            var principalParameter = principal.HasValue ?
                new ObjectParameter("Principal", principal) :
                new ObjectParameter("Principal", typeof(double));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("Mes", mes) :
                new ObjectParameter("Mes", typeof(int));
    
            var interesParameter = interes.HasValue ?
                new ObjectParameter("Interes", interes) :
                new ObjectParameter("Interes", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TablaAmortizacion", principalParameter, mesParameter, interesParameter);
        }
    }
}
