//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmortizacionDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int IdPrestamo { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> Principal { get; set; }
        public Nullable<double> Cuota { get; set; }
        public Nullable<decimal> Interes { get; set; }
        public Nullable<decimal> TasaInteres { get; set; }
        public Nullable<double> AportePrincipal { get; set; }
        public Nullable<double> SaldoFinal { get; set; }
    }
}
